library(sqldf)
desiredData <- read.csv.sql(file = "household_power_consumption.txt", header = T,sep = ";",sql = "select * from file where Date = '1/2/2007' or date = '2/2/2007'")
dataTimestamp <- paste(desiredData$Date,desiredData$Time)
drops <- c("Date","Time")
newData <- desiredData[,!(names(desiredData) %in% drops)]
times <- strptime(x = dataTimestamp,format = "%d/%m/%Y %H:%M:%S")
newData <- cbind(times,newData)
png(filename = "plot3.png", bg = "transparent")
plot(newData$Sub_metering_1 ~ newData$times,type="n",ylab = "Energy sub metring",xlab = NA)
lines(newData$Sub_metering_1 ~ newData$times, col = "black")
lines(newData$Sub_metering_2 ~ newData$times,col = "Red")
lines(newData$Sub_metering_3 ~ newData$times,col = "Blue")
legend("topright", col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = c(1,1,1))
dev.off()